#!/usr/bin/env osascript

on run argv
  if (count of argv) is 0 then return -- nothing to do

  set targetId to item 1 of argv as text

  tell application "iTerm2"
    repeat with aWindow in windows
      repeat with aTab in tabs of aWindow
        repeat with aSession in sessions of aTab
          set thisId to (id of aSession as text)
          if thisId is equal to targetId then
            tell aWindow to select
            tell aTab to select
            tell aSession to select
            activate
            return
          end if
        end repeat
      end repeat
    end repeat
  end tell
end run
